type Blog {
  id: String
  title: String
  author: String
  publish: String
}

input NewBlog {
  title: String!
  author: String!
  publish: String!
}

input UpdateBlog {
  id: String!
  title: String
  author: String
  publish: String
}

type Query {
  blogs: [Blog]
  getBlog(id: String): Blog
}
